version: '3'
services:
  nginx:
    image: "nginx:1.9"
    ports:
      - 80:80
    volumes:
      - ./sites/:/etc/nginx/conf.d:ro
    networks:
      - compartida
    restart: always

networks:
  compartida:
    external: true